name: Check watch
on: 
  schedule:
    - cron: '*/10 * * * *'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check for watch
          run: npm install && npm run task
      - name: Watch is there!!!
        if: success()
        uses: appleboy/telegram-action@master
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: "buy https://www.swatch.com/nl-nl/mission-to-the-moon-so33m100/SO33M100.html"
